services:
  arroyo-builder:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    volumes:
      - builder-cache:/usr/local/cargo/registry
      - target-cache:/app/target

  arroyo:
    image: arroyo
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: arroyo
    depends_on:
      - arroyo-builder

volumes:
  builder-cache:
  target-cache:
